
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shamsu and jack
 */
public class AllocateSlot extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
    /**
     * Creates new form Home
     */
    public AllocateSlot() {
        initComponents();
        fetchStatus();
        
    }
    public void fetch(){
    try {
        conn=DriverManager.getConnection("jdbc:mysql://localhost/parking","root","");
        String query="SELECT * FROM slot";
        pst=conn.prepareStatement(query);
        ResultSet rs=pst.executeQuery();
        DefaultTableModel model=(DefaultTableModel) Tableslot.getModel();
        model.setRowCount(0);
        while(rs.next())
        {
            Object[] content={rs.getString(1),rs.getString(2),rs.getString(3)};
            model.addRow(content);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null,ex);
        
    }
        
        
    }
      public void fetchStatus(){
    try {
        conn=DriverManager.getConnection("jdbc:mysql://localhost/parking","root","");
        String query="SELECT * FROM slot";
        pst=conn.prepareStatement(query);
        ResultSet rs=pst.executeQuery();
        DefaultTableModel model=(DefaultTableModel) TableStatus.getModel();
        model.setRowCount(0);
        while(rs.next())
        {
            Object[] content={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
            model.addRow(content);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null,ex);
        
    }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tableslot = new javax.swing.JTable();
        slotsizesave = new javax.swing.JTextField();
        locationsave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        slotnumber = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableStatus = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN HOME :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(38, 44, 150, 22);

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("WELCOME TO OUR PARKING SYSTEM.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(414, 0, 358, 26);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel6.setText("HERE IN THIS PAGE YOU CAN ADD SLOT AND ALSO  VIEW THE STATUS OF SLOTS OR PARKING");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(217, 44, 760, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1490, 110);

        jPanel2.setLayout(null);

        Tableslot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SlotNumber", "SlotSize", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tableslot);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(200, 60, 1110, 350);

        slotsizesave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotsizesaveActionPerformed(evt);
            }
        });
        jPanel2.add(slotsizesave);
        slotsizesave.setBounds(10, 180, 100, 30);

        locationsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationsaveActionPerformed(evt);
            }
        });
        jPanel2.add(locationsave);
        locationsave.setBounds(10, 260, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Location:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 220, 100, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("SlotSize:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 140, 100, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("SlotNumber:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 60, 120, 30);

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save);
        save.setBounds(90, 340, 90, 40);

        slotnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotnumberActionPerformed(evt);
            }
        });
        jPanel2.add(slotnumber);
        slotnumber.setBounds(10, 100, 100, 30);

        jTabbedPane1.addTab("ADD SLOT", jPanel2);

        jPanel3.setLayout(null);

        TableStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SlotNumber", "SlotSize", "Location", "Status", "ArrivalTime", "Duration", "Phone number Of Driver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableStatus);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 32, 940, 380);

        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(880, 420, 100, 26);

        jTabbedPane1.addTab("VIEW STATUS", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 120, 1450, 480);

        setSize(new java.awt.Dimension(1082, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void slotsizesaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotsizesaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slotsizesaveActionPerformed

    private void locationsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationsaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationsaveActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
         try {
        // TODO add your handling code here:
        conn=DriverManager.getConnection("jdbc:mysql://localhost/parking","root","");
        String sql="INSERT INTO Slot SET SlotNo=?,SlotSize=?,Location=?";
        pst=conn.prepareStatement(sql);
        pst.setString(1,slotnumber.getText());
        pst.setString(2,slotsizesave.getText());
        pst.setString(3,locationsave.getText());
        pst.executeUpdate();
        fetch();
        fetchStatus();
    } catch (Exception ex) {
       JOptionPane.showMessageDialog(null,ex);
    }
        
    }//GEN-LAST:event_saveActionPerformed

    private void slotnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slotnumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fetchStatus();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllocateSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllocateSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllocateSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllocateSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllocateSlot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableStatus;
    private javax.swing.JTable Tableslot;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField locationsave;
    private javax.swing.JButton save;
    private javax.swing.JTextField slotnumber;
    private javax.swing.JTextField slotsizesave;
    // End of variables declaration//GEN-END:variables
}
