
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shamsu
 */
public class Parkplace extends javax.swing.JFrame {

    /**
     * Here is where i declare my conn, which stands for connection and pst stands for prepared statement
     */
    Connection conn=null;
  PreparedStatement pst=null;
    public Parkplace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pnumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        cword = new javax.swing.JPasswordField();
        btnsubmit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        yemail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ypassword = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        btnenter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("     WELCOME TO PARKING MANAGEMENT SYSTEM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(8, 12, 530, 30);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        jLabel3.setText("SIGN UP");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(227, 61, 165, 41);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("FIRST NAME :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(88, 135, 95, 14);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname);
        fname.setBounds(227, 133, 109, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("LAST NAME :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(88, 188, 95, 14);

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel1.add(lname);
        lname.setBounds(227, 186, 109, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("PHONE NUMBER :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(88, 237, 110, 14);

        pnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnumberActionPerformed(evt);
            }
        });
        jPanel1.add(pnumber);
        pnumber.setBounds(227, 235, 109, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("EMAIL :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(88, 292, 50, 14);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(88, 326, 248, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("PASSWORD :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(88, 377, 80, 14);

        pword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwordActionPerformed(evt);
            }
        });
        jPanel1.add(pword);
        pword.setBounds(88, 405, 183, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("CONFIRM PASSWORD :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(88, 462, 140, 14);

        cword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwordActionPerformed(evt);
            }
        });
        jPanel1.add(cword);
        cword.setBounds(88, 496, 185, 30);

        btnsubmit.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit);
        btnsubmit.setBounds(390, 654, 148, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 710);

        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jLabel2.setText("SERVICE SPECIAL FOR YOU");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(12, 12, 347, 27);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel11.setText("WE CARE AND WE LOVE YOU");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(102, 75, 158, 16);

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel12.setText("LOGIN HERE");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(53, 151, 207, 20);

        jLabel13.setText("ENTER YOUR EMAIL :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(53, 221, 207, 16);

        yemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yemailActionPerformed(evt);
            }
        });
        jPanel3.add(yemail);
        yemail.setBounds(53, 272, 207, 30);

        jLabel14.setText("ENTER YOUR PASSWORD :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(53, 357, 150, 16);

        ypassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ypasswordActionPerformed(evt);
            }
        });
        jPanel3.add(ypassword);
        ypassword.setBounds(53, 411, 175, 30);

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel15.setText("PRESS ENTER TO LOGIN");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(149, 516, 128, 14);

        btnenter.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        btnenter.setText("ENTER");
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });
        jPanel3.add(btnenter);
        btnenter.setBounds(253, 582, 106, 38);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(690, 0, 370, 690);

        setSize(new java.awt.Dimension(1082, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cwordActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void pnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnumberActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void pwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwordActionPerformed
    
    //Here in this function are the codes that performs the action performed in batton submit, to submit details of the user to the database

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
         try{
            conn=DriverManager.getConnection("jdbc:mysql://localhost/Parking","root","");
            String sql="INSERT INTO driver(PhoneNumber,FirstName,Surname,Email,Password) VALUES(?,?,?,?,?)";
           pst=conn.prepareStatement(sql);
           pst.setString(1,pnumber.getText());
           pst.setString(2,fname.getText());
           pst.setString(3,lname.getText());
           pst.setString(4,email.getText());
           pst.setString(5,pword.getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null,"SUCCESSFULLY REGISTERED");
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void yemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yemailActionPerformed

    private void ypasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ypasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ypasswordActionPerformed
    
    //These codes performs functions which is used by the user or admin to enter or login to the system

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenterActionPerformed
        try {
            // TODO add your handling code here:
            conn=DriverManager.getConnection("jdbc:mysql://localhost/parking","root","");
            PreparedStatement adminpst;
            String sql="SELECT * FROM Driver WHERE Email=? AND Password=? ";
            String adminsql="SELECT * FROM Admin WHERE Email=? AND Password=?";
             pst=conn.prepareStatement(sql);
             adminpst=conn.prepareStatement(adminsql);
             adminpst.setString(1,yemail.getText());
             adminpst.setString(2,ypassword.getText());
            pst.setString(1,yemail.getText());
            pst.setString(2,ypassword.getText());
            ResultSet adminrs=adminpst.executeQuery();
            ResultSet rs=pst.executeQuery();
            
            //These conditions here is test for the details of the user or admin in the database when he or she want to login and if it is true can allow to login
            
            if(rs.next())
            {
                String DriverName=rs.getString(1);
                DriverHome dereva=new DriverHome();
                dereva.setVisible(true);
            }
            else if(adminrs.next())
            {
                AllocateSlot admini=new AllocateSlot();
                admini.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Email OR Password is wrong");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_btnenterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parkplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parkplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parkplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parkplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parkplace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JTextField cword;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField pnumber;
    private javax.swing.JTextField pword;
    private javax.swing.JTextField yemail;
    private javax.swing.JTextField ypassword;
    // End of variables declaration//GEN-END:variables
}
