
import static java.lang.Double.parseDouble;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shamsu
 */
public class Payment extends javax.swing.JFrame {
Connection conn=null;
    PreparedStatement pst=null;
    /**
     * Creates new form payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BankPayment = new javax.swing.JComboBox<>();
        MobilePayment = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hourchoose = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mylabel = new javax.swing.JLabel();
        btnhrs = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        priceshow = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        phonenumber = new javax.swing.JTextField();
        slotchoosen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        slotNumber = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("PAYMENT-PAGE");

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 12)); // NOI18N
        jLabel12.setText("HERE YOU CAN SELECT OR CHOOSE HOURS YOU WANT AND MAKE PAYMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 1050, 67);

        jLabel4.setText("PAYMENT METHODS:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 280, 120, 30);

        BankPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANK PAYMENT", "NMB", "CRDB", "BARCLAYS", "NBC", "DTB" }));
        BankPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(BankPayment);
        BankPayment.setBounds(20, 430, 400, 30);

        MobilePayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOBILE PAYMENT", "TigoPesa", "M-pesa", "AirtelMoney", "Halopesa", "EzyPesa" }));
        MobilePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobilePaymentActionPerformed(evt);
            }
        });
        getContentPane().add(MobilePayment);
        MobilePayment.setBounds(20, 360, 400, 30);

        jLabel3.setText("NOTE: 1hr=5,000Tsh;");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 540, 30);

        jLabel5.setText("Choose Hours :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 150, 90, 30);
        getContentPane().add(hourchoose);
        hourchoose.setBounds(90, 150, 50, 30);

        jLabel6.setText("You Have Choose:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 200, 110, 30);

        jLabel8.setText("HRS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 210, 40, 20);
        getContentPane().add(mylabel);
        mylabel.setBounds(130, 210, 40, 20);

        btnhrs.setText("CONFIRM");
        btnhrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhrsActionPerformed(evt);
            }
        });
        getContentPane().add(btnhrs);
        btnhrs.setBounds(400, 140, 130, 40);

        jLabel7.setText("Equivalent to:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 210, 80, 20);
        getContentPane().add(priceshow);
        priceshow.setBounds(340, 210, 40, 20);

        jLabel9.setText("Tsh");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 210, 60, 20);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 490, 120, 50);

        jLabel10.setText("Choose method of payment you want to use;");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 310, 250, 14);

        jLabel11.setText("Enter You Currently Phone Number:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 250, 190, 30);

        phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumberActionPerformed(evt);
            }
        });
        getContentPane().add(phonenumber);
        phonenumber.setBounds(210, 250, 200, 30);
        getContentPane().add(slotchoosen);
        slotchoosen.setBounds(270, 150, 90, 30);

        jLabel13.setText("Slot Number:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(450, 210, 90, 20);

        jLabel14.setText("Slot Number:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(190, 150, 70, 20);
        getContentPane().add(slotNumber);
        slotNumber.setBounds(550, 200, 50, 30);

        setSize(new java.awt.Dimension(1082, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BankPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankPaymentActionPerformed
        // TODO add your handling code here:
        String BankPaymentMethod=BankPayment.getSelectedItem().toString();
    }//GEN-LAST:event_BankPaymentActionPerformed

    private void MobilePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobilePaymentActionPerformed
        // TODO add your handling code here:
        String MobilePaymentMethod=MobilePayment.getSelectedItem().toString();
    }//GEN-LAST:event_MobilePaymentActionPerformed

    private void btnhrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhrsActionPerformed
        // TODO add your handling code here:
        String hrs=hourchoose.getValue().toString();
        mylabel.setText(hrs);
        int hour=(int) Double.parseDouble(hrs);
         int FinalPrice=hour*5000;
         String finalprice=String.valueOf(FinalPrice);
         priceshow.setText(finalprice);
         String Slot=slotchoosen.getText();
         slotNumber.setText(Slot);
        
    }//GEN-LAST:event_btnhrsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            conn=DriverManager.getConnection("jdbc:mysql://localhost/parking","root","");
        String sql="INSERT INTO payment(Period,Price,PaymentMethod,PayerPhone) VALUES (?,?,?,?)";
        pst=conn.prepareStatement(sql);
       pst.setString(1,hourchoose.getValue().toString());
       pst.setString(2,priceshow.getText());
       pst.setString(3,BankPayment.getSelectedItem().toString());
        pst.setString(3,MobilePayment.getSelectedItem().toString());
        pst.setString(4,phonenumber.getText());
        pst.executeUpdate();
        String SlotN=slotchoosen.getText();
         String hrs=hourchoose.getValue().toString();
         DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now();
        String time=dtf.format(now);
        String Dphone=phonenumber.getText();
        String query="UPDATE slot SET status=?,ArrivalTime=?,Duration=?,DriverPhone=? WHERE slotNo=?";
        PreparedStatement pstE=conn.prepareStatement(query); 
        pstE.setString(1,"Paid");
        pstE.setString(2,time);
        pstE.setString(3,hrs);
        pstE.setString(4,Dphone);
        pstE.setString(5,SlotN);
         pstE.execute();
        JOptionPane.showMessageDialog(null,"YOU HAVE SUCCESSFULLY PAID AT SLOT NUMBER"+" "+SlotN+" "+"From"+" "+" "+dtf.format(now)+" "+" "+"FOR ONLY"+" "+" "+hrs+ "Hours");
      
        
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex);
        }
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void phonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BankPayment;
    private javax.swing.JComboBox<String> MobilePayment;
    private javax.swing.JButton btnhrs;
    private javax.swing.JSpinner hourchoose;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mylabel;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JLabel priceshow;
    private javax.swing.JLabel slotNumber;
    private javax.swing.JTextField slotchoosen;
    // End of variables declaration//GEN-END:variables
}
